const mongoose = require('mongoose');

const EngineerSchema = new mongoose.Schema(
    {
        firstName: { type: String, required: true, trim: true },
        lastName: { type: String, required: true, trim: true },
        email: { type: String, required: true, trim: true, lowercase: true, unique: true },
        phone: { type: String, required: true, trim: true },
        discipline: { type: String, required: true },
        licenseNumber: { type: String, default: '' },
        yearsExperience: { type: Number, default: 0 },
        city: { type: String, required: true, trim: true },
        country: { type: String, required: true, trim: true },
        password: { type: String, required: true },

        // Mobile App fields
        location: {
            type: {
                type: String,
                enum: ['Point'],
                default: 'Point',
            },
            coordinates: {
                type: [Number],
                default: [0, 0], // [longitude, latitude]
            }
        },
        isOnline: { type: Boolean, default: false },
        earnings: { type: Number, default: 0 },
        acceptedCount: { type: Number, default: 0 },
        rejectedCount: { type: Number, default: 0 },

        // Degree upload — unique filename generated by server
        degreeFilename: { type: String, default: null },
        degreeOriginalName: { type: String, default: null },

        agreedToTerms: { type: Boolean, required: true, default: false },

        status: {
            type: String,
            enum: ['Pending', 'Active', 'Inactive', 'Rejected'],
            default: 'Pending',
        },
    },
    { timestamps: true }
);

EngineerSchema.index({ location: '2dsphere' });

module.exports = mongoose.model('Engineer', EngineerSchema);
